- name: Upload new code and restart
  hosts: web
  vars:
    app: apache2
  tasks:
    - name: place custom webpages
      synchronize:
        src: "/mnt/c/ProgramData/Jenkins/.jenkins/workspace/git_update/03-EBook-Site/"
        dest: /var/www/html/
        recursive: yes
      become: true

    - name: start the service
      service:
        name: apache2
        state: restarted
        enabled: yes
      become: true





# creating users and pasting the respective ssh_keys in the users..and ensuring that the .ssh and authorized_keys are there
- name: creating users
  hosts: demo-server
  vars:
    user_data: "{{ lookup('file', 'user_data.yml') }}"
  tasks:
  - name: creating users
    user:
      name: "{{ item.username }}"
      shell: /bin/bash
      state: present
    loop: "{{ user_data.users }}"

  - name: creating ssh folder
    file:
      shell: mkdir /home/{{ item.username }}/.ssh
      state: directory
      mode: "0700"
      owner: "{{ item.username }}"
      group: "{{}item.username }"
    loop: "{{ user_data.users }}"
    
  
  - name: creating authorized_keys file
    file:
      shell: touch /home/{{ item.username }}/.ssh/authorized_keys
      state: present
      mode: "0644"
      owner: "{{ item.username }}"
      group: "{{ item.username }}"
    loop: "{{ user_data.users }}"

  - name: pasting ssh_keys into the respective users account
    lineinfile: 
      path: /home/{{ item.username/.ssh/authorized_keys }}
      line: "{{ item.ssh_keys }}"
    loop: "{{ user_data.users }}"

#script to take input from the sys admins..input(username & ssh_key)
#!/bin/bash

echo "users:" > user_data.yml
read -p "total users" total_users

if [[ "$total_users" -gt 0 ]]; then
  for(( int i=1; i<=$total_users; i++ )); 
  do 
    read -p "Enter username" username
    read -p "Enter ssh_key(pub)" ssh_key

    echo "  - username: $username" >> user_data.yml
    echo "    ssh_keys: $ssh_key" >> user_data.yml

    echo "posted succefully"
  done
else
  echo "enter some numbers brotherrr"
fi
        
      



























